export default [{
  "first_name": "Oralie",
  "last_name": "Trenam",
  "job_title": "otrenam0@ustream.tv",
  "company": "Keeling-Erdman",
  "business_email": "otrenam0@ovh.net",
  "personal_email": "otrenam0@friendfeed.com",
  "business_phone": "2275924591",
  "personal_phone": "3513502644",
  "address": "6 Jenna Junction",
  "linked_in": "",
  "created_at": "2024-05-29 02:34:49",
  "id": 1,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Shanon",
  "last_name": "Padula",
  "job_title": "spadula1@freewebs.com",
  "company": "Bogan LLC",
  "business_email": "spadula1@amazon.de",
  "personal_email": "spadula1@army.mil",
  "business_phone": "4104489377",
  "personal_phone": "8758225410",
  "address": "5 Amoth Crossing",
  "linked_in": "",
  "created_at": "2024-01-16 22:16:14",
  "id": 2,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Randy",
  "last_name": "Gallymore",
  "job_title": "rgallymore2@google.it",
  "company": "Collier Inc",
  "business_email": "rgallymore2@mail.ru",
  "personal_email": "rgallymore2@lulu.com",
  "business_phone": "5932994398",
  "personal_phone": "8752953087",
  "address": "23415 Bellgrove Park",
  "linked_in": "",
  "created_at": "2024-02-03 04:54:13",
  "id": 3,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Quincy",
  "last_name": "Cavnor",
  "job_title": "qcavnor3@ask.com",
  "company": "Greenfelder-Heathcote",
  "business_email": "qcavnor3@bizjournals.com",
  "personal_email": "qcavnor3@squidoo.com",
  "business_phone": "5813402740",
  "personal_phone": "5716178383",
  "address": "21 Sugar Alley",
  "linked_in": "",
  "created_at": "2024-09-14 21:54:31",
  "id": 4,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Ruthy",
  "last_name": "Esherwood",
  "job_title": "resherwood4@gmpg.org",
  "company": "Davis, Ziemann and Kuhn",
  "business_email": "resherwood4@google.nl",
  "personal_email": "resherwood4@baidu.com",
  "business_phone": "8321690054",
  "personal_phone": "3897519115",
  "address": "6696 Calypso Park",
  "linked_in": "",
  "created_at": "2024-09-04 08:39:13",
  "id": 5,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Felicity",
  "last_name": "Derrell",
  "job_title": "fderrell5@toplist.cz",
  "company": "Bode Inc",
  "business_email": "fderrell5@comsenz.com",
  "personal_email": "fderrell5@salon.com",
  "business_phone": "8375169145",
  "personal_phone": "1251379548",
  "address": "54 Ludington Road",
  "linked_in": "",
  "created_at": "2024-09-27 19:01:42",
  "id": 6,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Boyd",
  "last_name": "Ives",
  "job_title": "bives6@dell.com",
  "company": "Carter, O'Conner and Mann",
  "business_email": "bives6@facebook.com",
  "personal_email": "bives6@wordpress.org",
  "business_phone": "4484806710",
  "personal_phone": "2231069539",
  "address": "1220 Birchwood Point",
  "linked_in": "",
  "created_at": "2023-12-06 11:01:08",
  "id": 7,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Gertrud",
  "last_name": "Eastcott",
  "job_title": "geastcott7@xrea.com",
  "company": "Donnelly, Marquardt and Pacocha",
  "business_email": "geastcott7@ustream.tv",
  "personal_email": "geastcott7@china.com.cn",
  "business_phone": "6521693796",
  "personal_phone": "2705491703",
  "address": "47 Carberry Trail",
  "linked_in": "",
  "created_at": "2024-06-09 09:35:59",
  "id": 8,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Maddalena",
  "last_name": "Quoit",
  "job_title": "mquoit8@intel.com",
  "company": "Johnston Inc",
  "business_email": "mquoit8@ca.gov",
  "personal_email": "mquoit8@ibm.com",
  "business_phone": "2897765038",
  "personal_phone": "9617304097",
  "address": "87224 Messerschmidt Center",
  "linked_in": "",
  "created_at": "2023-12-30 05:43:05",
  "id": 9,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Emery",
  "last_name": "MacCrann",
  "job_title": "emaccrann9@businessweek.com",
  "company": "Simonis LLC",
  "business_email": "emaccrann9@reverbnation.com",
  "personal_email": "emaccrann9@bloglovin.com",
  "business_phone": "4627770807",
  "personal_phone": "9795695083",
  "address": "8 Maryland Lane",
  "linked_in": "",
  "created_at": "2024-06-10 03:53:40",
  "id": 10,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Dena",
  "last_name": "Durker",
  "job_title": "ddurkera@facebook.com",
  "company": "Torp LLC",
  "business_email": "ddurkera@va.gov",
  "personal_email": "ddurkera@dot.gov",
  "business_phone": "5407906368",
  "personal_phone": "3433314305",
  "address": "4 Thierer Place",
  "linked_in": "",
  "created_at": "2024-06-24 12:57:09",
  "id": 11,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Alon",
  "last_name": "Gricks",
  "job_title": "agricksb@spotify.com",
  "company": "Ziemann, Metz and Kautzer",
  "business_email": "agricksb@mlb.com",
  "personal_email": "agricksb@fda.gov",
  "business_phone": "6888946415",
  "personal_phone": "4601987535",
  "address": "871 Melrose Avenue",
  "linked_in": "",
  "created_at": "2024-03-12 15:59:23",
  "id": 12,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Chip",
  "last_name": "Gelland",
  "job_title": "cgellandc@blog.com",
  "company": "Zieme, Howe and Harber",
  "business_email": "cgellandc@nasa.gov",
  "personal_email": "cgellandc@tumblr.com",
  "business_phone": "5003097489",
  "personal_phone": "5729401743",
  "address": "62 7th Circle",
  "linked_in": "",
  "created_at": "2024-10-02 11:47:20",
  "id": 13,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Hildagarde",
  "last_name": "Bamlet",
  "job_title": "hbamletd@alibaba.com",
  "company": "Nienow-Koch",
  "business_email": "hbamletd@fema.gov",
  "personal_email": "hbamletd@oracle.com",
  "business_phone": "9625608461",
  "personal_phone": "8808093451",
  "address": "04 Carey Court",
  "linked_in": "",
  "created_at": "2023-11-06 14:15:38",
  "id": 14,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Nicoline",
  "last_name": "Jiras",
  "job_title": "njirase@jalbum.net",
  "company": "Murray, Ebert and Reichert",
  "business_email": "njirase@a8.net",
  "personal_email": "njirase@eventbrite.com",
  "business_phone": "7486493397",
  "personal_phone": "9042016742",
  "address": "97 Porter Park",
  "linked_in": "",
  "created_at": "2024-10-14 00:36:08",
  "id": 15,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Tybalt",
  "last_name": "Cassidy",
  "job_title": "tcassidyf@etsy.com",
  "company": "Ratke Group",
  "business_email": "tcassidyf@forbes.com",
  "personal_email": "tcassidyf@hexun.com",
  "business_phone": "2657631659",
  "personal_phone": "8628557628",
  "address": "9511 Clemons Way",
  "linked_in": "",
  "created_at": "2024-01-27 15:14:56",
  "id": 16,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Jaynell",
  "last_name": "Enston",
  "job_title": "jenstong@ihg.com",
  "company": "Metz Group",
  "business_email": "jenstong@webmd.com",
  "personal_email": "jenstong@people.com.cn",
  "business_phone": "4493368116",
  "personal_phone": "3515107049",
  "address": "1 Shopko Alley",
  "linked_in": "",
  "created_at": "2023-12-10 09:58:18",
  "id": 17,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Sheridan",
  "last_name": "Kidner",
  "job_title": "skidnerh@infoseek.co.jp",
  "company": "Moore, Lockman and Streich",
  "business_email": "skidnerh@wikipedia.org",
  "personal_email": "skidnerh@networksolutions.com",
  "business_phone": "6404077073",
  "personal_phone": "7165754474",
  "address": "301 Hayes Drive",
  "linked_in": "",
  "created_at": "2023-11-19 07:11:42",
  "id": 18,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Natka",
  "last_name": "Shearer",
  "job_title": "nsheareri@sfgate.com",
  "company": "Kemmer LLC",
  "business_email": "nsheareri@techcrunch.com",
  "personal_email": "nsheareri@google.cn",
  "business_phone": "1917132428",
  "personal_phone": "9953286109",
  "address": "96663 Tennyson Pass",
  "linked_in": "",
  "created_at": "2024-01-04 22:47:57",
  "id": 19,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Jayson",
  "last_name": "Pinor",
  "job_title": "jpinorj@macromedia.com",
  "company": "Hodkiewicz-Prosacco",
  "business_email": "jpinorj@bbc.co.uk",
  "personal_email": "jpinorj@who.int",
  "business_phone": "1501014204",
  "personal_phone": "3311954209",
  "address": "457 Loeprich Parkway",
  "linked_in": "",
  "created_at": "2024-08-23 15:33:50",
  "id": 20,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Sileas",
  "last_name": "Tomblings",
  "job_title": "stomblingsk@symantec.com",
  "company": "Morar Inc",
  "business_email": "stomblingsk@timesonline.co.uk",
  "personal_email": "stomblingsk@google.cn",
  "business_phone": "9705116281",
  "personal_phone": "8267545102",
  "address": "77 Truax Parkway",
  "linked_in": "",
  "created_at": "2024-01-23 21:25:08",
  "id": 21,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Shaun",
  "last_name": "Parrot",
  "job_title": "sparrotl@trellian.com",
  "company": "Reilly-Schmidt",
  "business_email": "sparrotl@prweb.com",
  "personal_email": "sparrotl@about.me",
  "business_phone": "1174015974",
  "personal_phone": "1959235120",
  "address": "051 Main Place",
  "linked_in": "",
  "created_at": "2024-07-02 20:14:27",
  "id": 22,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Tiffi",
  "last_name": "Hardiman",
  "job_title": "thardimanm@tumblr.com",
  "company": "Predovic and Sons",
  "business_email": "thardimanm@mac.com",
  "personal_email": "thardimanm@businesswire.com",
  "business_phone": "8604006378",
  "personal_phone": "4039595288",
  "address": "32 Montana Point",
  "linked_in": "",
  "created_at": "2024-04-12 20:17:58",
  "id": 23,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Kellia",
  "last_name": "Assard",
  "job_title": "kassardn@ebay.com",
  "company": "Erdman Inc",
  "business_email": "kassardn@sun.com",
  "personal_email": "kassardn@bloomberg.com",
  "business_phone": "9746480742",
  "personal_phone": "5572729379",
  "address": "18 Pleasure Street",
  "linked_in": "",
  "created_at": "2024-06-10 19:25:48",
  "id": 24,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Forrest",
  "last_name": "Checcucci",
  "job_title": "fcheccuccio@ucoz.com",
  "company": "Ryan, Heathcote and Durgan",
  "business_email": "fcheccuccio@plala.or.jp",
  "personal_email": "fcheccuccio@unblog.fr",
  "business_phone": "2558025722",
  "personal_phone": "8509270518",
  "address": "3466 Summerview Point",
  "linked_in": "",
  "created_at": "2024-04-20 10:47:56",
  "id": 25,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Myrvyn",
  "last_name": "Delucia",
  "job_title": "mdeluciap@pcworld.com",
  "company": "Larson-Yundt",
  "business_email": "mdeluciap@japanpost.jp",
  "personal_email": "mdeluciap@jalbum.net",
  "business_phone": "2918092497",
  "personal_phone": "8957831419",
  "address": "369 Sutteridge Parkway",
  "linked_in": "",
  "created_at": "2024-06-10 13:40:26",
  "id": 26,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Dur",
  "last_name": "Sadd",
  "job_title": "dsaddq@zdnet.com",
  "company": "Gleason LLC",
  "business_email": "dsaddq@samsung.com",
  "personal_email": "dsaddq@acquirethisname.com",
  "business_phone": "3937551710",
  "personal_phone": "4473370881",
  "address": "2 Old Shore Lane",
  "linked_in": "",
  "created_at": "2024-10-15 01:13:00",
  "id": 27,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Jacinthe",
  "last_name": "Hune",
  "job_title": "jhuner@shareasale.com",
  "company": "Gerhold Inc",
  "business_email": "jhuner@answers.com",
  "personal_email": "jhuner@wikia.com",
  "business_phone": "2233305615",
  "personal_phone": "2362167647",
  "address": "44 Victoria Terrace",
  "linked_in": "",
  "created_at": "2024-02-22 20:37:20",
  "id": 28,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Marcille",
  "last_name": "Gibling",
  "job_title": "mgiblings@lulu.com",
  "company": "Botsford-Reichel",
  "business_email": "mgiblings@so-net.ne.jp",
  "personal_email": "mgiblings@deviantart.com",
  "business_phone": "1329693516",
  "personal_phone": "4346994380",
  "address": "069 Porter Place",
  "linked_in": "",
  "created_at": "2024-07-08 02:45:37",
  "id": 29,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Leonid",
  "last_name": "Batchelour",
  "job_title": "lbatchelourt@163.com",
  "company": "Hickle Inc",
  "business_email": "lbatchelourt@alexa.com",
  "personal_email": "lbatchelourt@tripod.com",
  "business_phone": "3263194440",
  "personal_phone": "2594961454",
  "address": "89 Oak Plaza",
  "linked_in": "",
  "created_at": "2024-05-26 02:07:02",
  "id": 30,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Teri",
  "last_name": "Baison",
  "job_title": "tbaisonu@un.org",
  "company": "Windler, Doyle and Mohr",
  "business_email": "tbaisonu@pbs.org",
  "personal_email": "tbaisonu@shop-pro.jp",
  "business_phone": "5413594300",
  "personal_phone": "6808539214",
  "address": "211 Lawn Way",
  "linked_in": "",
  "created_at": "2023-12-20 20:43:13",
  "id": 31,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Latashia",
  "last_name": "Oolahan",
  "job_title": "loolahanv@indiegogo.com",
  "company": "Windler, Hintz and Cormier",
  "business_email": "loolahanv@bbb.org",
  "personal_email": "loolahanv@myspace.com",
  "business_phone": "6268990026",
  "personal_phone": "5425571682",
  "address": "5 Superior Place",
  "linked_in": "",
  "created_at": "2024-02-20 15:04:48",
  "id": 32,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Hedi",
  "last_name": "Hubbock",
  "job_title": "hhubbockw@kickstarter.com",
  "company": "Rutherford LLC",
  "business_email": "hhubbockw@dropbox.com",
  "personal_email": "hhubbockw@geocities.jp",
  "business_phone": "2088033996",
  "personal_phone": "7711098054",
  "address": "2 Tennyson Lane",
  "linked_in": "",
  "created_at": "2024-04-07 03:43:26",
  "id": 33,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Cal",
  "last_name": "Spyvye",
  "job_title": "cspyvyex@weibo.com",
  "company": "Conn, Kutch and Rolfson",
  "business_email": "cspyvyex@vinaora.com",
  "personal_email": "cspyvyex@ted.com",
  "business_phone": "4051578471",
  "personal_phone": "1572856600",
  "address": "23 Merrick Point",
  "linked_in": "",
  "created_at": "2024-03-05 18:19:05",
  "id": 34,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Corry",
  "last_name": "Mcimmie",
  "job_title": "cmcimmiey@sina.com.cn",
  "company": "Crona, Gislason and Batz",
  "business_email": "cmcimmiey@miibeian.gov.cn",
  "personal_email": "cmcimmiey@webnode.com",
  "business_phone": "1238302990",
  "personal_phone": "2669214501",
  "address": "8564 Goodland Parkway",
  "linked_in": "",
  "created_at": "2024-09-04 09:28:16",
  "id": 35,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Averell",
  "last_name": "Wahlberg",
  "job_title": "awahlbergz@netvibes.com",
  "company": "Wiegand LLC",
  "business_email": "awahlbergz@shutterfly.com",
  "personal_email": "awahlbergz@wikispaces.com",
  "business_phone": "4262839855",
  "personal_phone": "4281619781",
  "address": "301 Kingsford Road",
  "linked_in": "",
  "created_at": "2024-05-27 07:40:46",
  "id": 36,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Barnebas",
  "last_name": "Pursglove",
  "job_title": "bpursglove10@vimeo.com",
  "company": "Halvorson-Kub",
  "business_email": "bpursglove10@ted.com",
  "personal_email": "bpursglove10@tinyurl.com",
  "business_phone": "5523132513",
  "personal_phone": "2644154856",
  "address": "45 Caliangt Avenue",
  "linked_in": "",
  "created_at": "2024-04-24 03:21:22",
  "id": 37,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Ashlie",
  "last_name": "Boot",
  "job_title": "aboot11@goo.gl",
  "company": "Leuschke Inc",
  "business_email": "aboot11@squidoo.com",
  "personal_email": "aboot11@toplist.cz",
  "business_phone": "9806491882",
  "personal_phone": "1327664861",
  "address": "73 Armistice Way",
  "linked_in": "",
  "created_at": "2023-12-10 22:17:58",
  "id": 38,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Onofredo",
  "last_name": "Kytter",
  "job_title": "okytter12@buzzfeed.com",
  "company": "Kunde Inc",
  "business_email": "okytter12@domainmarket.com",
  "personal_email": "okytter12@clickbank.net",
  "business_phone": "9978888516",
  "personal_phone": "9489581713",
  "address": "5216 Anzinger Court",
  "linked_in": "",
  "created_at": "2024-02-29 01:37:51",
  "id": 39,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Jamie",
  "last_name": "Dearman",
  "job_title": "jdearman13@exblog.jp",
  "company": "Fadel-MacGyver",
  "business_email": "jdearman13@altervista.org",
  "personal_email": "jdearman13@hibu.com",
  "business_phone": "8705860885",
  "personal_phone": "8249625475",
  "address": "46301 Blue Bill Park Circle",
  "linked_in": "",
  "created_at": "2024-01-04 13:02:17",
  "id": 40,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Heath",
  "last_name": "Wartnaby",
  "job_title": "hwartnaby14@sphinn.com",
  "company": "Olson Group",
  "business_email": "hwartnaby14@google.com.au",
  "personal_email": "hwartnaby14@blog.com",
  "business_phone": "3498630748",
  "personal_phone": "5673034197",
  "address": "377 Eastwood Junction",
  "linked_in": "",
  "created_at": "2024-03-18 22:56:33",
  "id": 41,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Leilah",
  "last_name": "Corkish",
  "job_title": "lcorkish15@prnewswire.com",
  "company": "Langosh-Hodkiewicz",
  "business_email": "lcorkish15@google.pl",
  "personal_email": "lcorkish15@stumbleupon.com",
  "business_phone": "4269494932",
  "personal_phone": "1682745574",
  "address": "79902 Nova Avenue",
  "linked_in": "",
  "created_at": "2024-09-25 18:36:56",
  "id": 42,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Karoly",
  "last_name": "McAllister",
  "job_title": "kmcallister16@example.com",
  "company": "Stanton Group",
  "business_email": "kmcallister16@bandcamp.com",
  "personal_email": "kmcallister16@instagram.com",
  "business_phone": "5648831961",
  "personal_phone": "6118544628",
  "address": "5 Loomis Terrace",
  "linked_in": "",
  "created_at": "2024-03-26 00:23:28",
  "id": 43,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Nathanial",
  "last_name": "Tennant",
  "job_title": "ntennant17@msn.com",
  "company": "Sanford and Sons",
  "business_email": "ntennant17@spotify.com",
  "personal_email": "ntennant17@t-online.de",
  "business_phone": "6018413628",
  "personal_phone": "8055521451",
  "address": "51 Kings Junction",
  "linked_in": "",
  "created_at": "2024-03-28 02:49:12",
  "id": 44,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Sayer",
  "last_name": "Matasov",
  "job_title": "smatasov18@earthlink.net",
  "company": "Rath and Sons",
  "business_email": "smatasov18@yellowpages.com",
  "personal_email": "smatasov18@dot.gov",
  "business_phone": "5157501006",
  "personal_phone": "5145437483",
  "address": "490 Hallows Court",
  "linked_in": "",
  "created_at": "2024-08-20 23:57:24",
  "id": 45,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Lucias",
  "last_name": "Luckett",
  "job_title": "lluckett19@istockphoto.com",
  "company": "Hermiston Group",
  "business_email": "lluckett19@booking.com",
  "personal_email": "lluckett19@wikispaces.com",
  "business_phone": "9142995075",
  "personal_phone": "8325268721",
  "address": "42544 Lakeland Drive",
  "linked_in": "",
  "created_at": "2024-09-23 06:17:47",
  "id": 46,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Valaria",
  "last_name": "Wicken",
  "job_title": "vwicken1a@indiegogo.com",
  "company": "Rolfson Group",
  "business_email": "vwicken1a@irs.gov",
  "personal_email": "vwicken1a@microsoft.com",
  "business_phone": "8494242639",
  "personal_phone": "4059397320",
  "address": "890 Derek Road",
  "linked_in": "",
  "created_at": "2024-07-13 09:57:33",
  "id": 47,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Delaney",
  "last_name": "Leetham",
  "job_title": "dleetham1b@constantcontact.com",
  "company": "Hickle, Waelchi and Champlin",
  "business_email": "dleetham1b@etsy.com",
  "personal_email": "dleetham1b@bing.com",
  "business_phone": "1487198867",
  "personal_phone": "7028249132",
  "address": "7 Kinsman Park",
  "linked_in": "",
  "created_at": "2024-05-03 13:50:56",
  "id": 48,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Haywood",
  "last_name": "Prendergrast",
  "job_title": "hprendergrast1c@squarespace.com",
  "company": "Thompson, Douglas and Goyette",
  "business_email": "hprendergrast1c@senate.gov",
  "personal_email": "hprendergrast1c@weather.com",
  "business_phone": "1895247318",
  "personal_phone": "1897965455",
  "address": "03520 Namekagon Way",
  "linked_in": "",
  "created_at": "2023-11-24 20:42:54",
  "id": 49,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Caritta",
  "last_name": "Rogier",
  "job_title": "crogier1d@scientificamerican.com",
  "company": "Schneider-Quigley",
  "business_email": "crogier1d@cam.ac.uk",
  "personal_email": "crogier1d@hibu.com",
  "business_phone": "6142430695",
  "personal_phone": "7028257362",
  "address": "68 Alpine Drive",
  "linked_in": "",
  "created_at": "2024-03-06 12:24:32",
  "id": 50,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Sutherlan",
  "last_name": "Radsdale",
  "job_title": "sradsdale1e@bizjournals.com",
  "company": "McDermott-Quigley",
  "business_email": "sradsdale1e@abc.net.au",
  "personal_email": "sradsdale1e@vinaora.com",
  "business_phone": "3768857849",
  "personal_phone": "2874735037",
  "address": "933 Independence Plaza",
  "linked_in": "",
  "created_at": "2024-08-06 10:02:58",
  "id": 51,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Tye",
  "last_name": "Honsch",
  "job_title": "thonsch1f@google.cn",
  "company": "Lowe Inc",
  "business_email": "thonsch1f@friendfeed.com",
  "personal_email": "thonsch1f@chronoengine.com",
  "business_phone": "8519809773",
  "personal_phone": "3893699487",
  "address": "97709 Kennedy Alley",
  "linked_in": "",
  "created_at": "2024-09-08 19:25:06",
  "id": 52,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Talya",
  "last_name": "Eccleshare",
  "job_title": "teccleshare1g@facebook.com",
  "company": "Greenholt, Harvey and Wehner",
  "business_email": "teccleshare1g@netscape.com",
  "personal_email": "teccleshare1g@google.com.br",
  "business_phone": "8716557815",
  "personal_phone": "3715492039",
  "address": "1 Ohio Circle",
  "linked_in": "",
  "created_at": "2023-11-19 14:07:23",
  "id": 53,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Sharon",
  "last_name": "Flahy",
  "job_title": "sflahy1h@discuz.net",
  "company": "Schoen-Shields",
  "business_email": "sflahy1h@vinaora.com",
  "personal_email": "sflahy1h@slate.com",
  "business_phone": "3405592260",
  "personal_phone": "6025585088",
  "address": "0 Express Drive",
  "linked_in": "",
  "created_at": "2023-11-27 13:17:56",
  "id": 54,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Nealon",
  "last_name": "Durrad",
  "job_title": "ndurrad1i@npr.org",
  "company": "Swift-Bartell",
  "business_email": "ndurrad1i@businessweek.com",
  "personal_email": "ndurrad1i@elegantthemes.com",
  "business_phone": "3177422407",
  "personal_phone": "2682694930",
  "address": "15417 Ruskin Crossing",
  "linked_in": "",
  "created_at": "2024-08-23 12:15:17",
  "id": 55,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Kordula",
  "last_name": "Keyson",
  "job_title": "kkeyson1j@google.ca",
  "company": "Reichert and Sons",
  "business_email": "kkeyson1j@samsung.com",
  "personal_email": "kkeyson1j@wp.com",
  "business_phone": "1012574063",
  "personal_phone": "2693059965",
  "address": "51159 Kingsford Road",
  "linked_in": "",
  "created_at": "2023-12-16 03:48:32",
  "id": 56,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Ferrell",
  "last_name": "Maddick",
  "job_title": "fmaddick1k@wordpress.com",
  "company": "Brakus-Koepp",
  "business_email": "fmaddick1k@livejournal.com",
  "personal_email": "fmaddick1k@discuz.net",
  "business_phone": "6526122634",
  "personal_phone": "3099956279",
  "address": "9475 Fulton Center",
  "linked_in": "",
  "created_at": "2023-10-26 08:01:17",
  "id": 57,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Walker",
  "last_name": "Gladwell",
  "job_title": "wgladwell1l@angelfire.com",
  "company": "Kutch-Mann",
  "business_email": "wgladwell1l@blogger.com",
  "personal_email": "wgladwell1l@yahoo.com",
  "business_phone": "4952617498",
  "personal_phone": "4453326433",
  "address": "3 Pleasure Hill",
  "linked_in": "",
  "created_at": "2024-03-28 15:53:16",
  "id": 58,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Chrissy",
  "last_name": "Sousa",
  "job_title": "csousa1m@about.me",
  "company": "Gerlach-Funk",
  "business_email": "csousa1m@unc.edu",
  "personal_email": "csousa1m@goodreads.com",
  "business_phone": "8823871014",
  "personal_phone": "9945292912",
  "address": "3 Kinsman Way",
  "linked_in": "",
  "created_at": "2024-04-02 19:55:40",
  "id": 59,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Sela",
  "last_name": "Pedwell",
  "job_title": "spedwell1n@techcrunch.com",
  "company": "Champlin, Donnelly and Kozey",
  "business_email": "spedwell1n@dmoz.org",
  "personal_email": "spedwell1n@hexun.com",
  "business_phone": "8156378631",
  "personal_phone": "5815042062",
  "address": "64 Lien Park",
  "linked_in": "",
  "created_at": "2023-11-22 03:22:49",
  "id": 60,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Gabrielle",
  "last_name": "Sibbet",
  "job_title": "gsibbet1o@yahoo.com",
  "company": "Wiegand-Wuckert",
  "business_email": "gsibbet1o@nationalgeographic.com",
  "personal_email": "gsibbet1o@drupal.org",
  "business_phone": "6034253306",
  "personal_phone": "1981573960",
  "address": "974 Sullivan Alley",
  "linked_in": "",
  "created_at": "2023-11-27 02:56:42",
  "id": 61,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Bonnibelle",
  "last_name": "Shere",
  "job_title": "bshere1p@drupal.org",
  "company": "Christiansen-Swift",
  "business_email": "bshere1p@yahoo.co.jp",
  "personal_email": "bshere1p@drupal.org",
  "business_phone": "6519647110",
  "personal_phone": "7069502372",
  "address": "7840 Johnson Point",
  "linked_in": "",
  "created_at": "2024-09-16 12:45:26",
  "id": 62,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Dorey",
  "last_name": "Toon",
  "job_title": "dtoon1q@barnesandnoble.com",
  "company": "Kohler Inc",
  "business_email": "dtoon1q@vistaprint.com",
  "personal_email": "dtoon1q@un.org",
  "business_phone": "4885089000",
  "personal_phone": "3836463900",
  "address": "33893 Kim Terrace",
  "linked_in": "",
  "created_at": "2024-04-09 22:09:02",
  "id": 63,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Ileana",
  "last_name": "Sonier",
  "job_title": "isonier1r@tripadvisor.com",
  "company": "Kilback, Boehm and Auer",
  "business_email": "isonier1r@accuweather.com",
  "personal_email": "isonier1r@constantcontact.com",
  "business_phone": "5946561221",
  "personal_phone": "3541611534",
  "address": "109 Norway Maple Plaza",
  "linked_in": "",
  "created_at": "2024-02-18 18:06:23",
  "id": 64,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Meredeth",
  "last_name": "Rhead",
  "job_title": "mrhead1s@last.fm",
  "company": "Dooley Inc",
  "business_email": "mrhead1s@shinystat.com",
  "personal_email": "mrhead1s@goo.ne.jp",
  "business_phone": "8713046265",
  "personal_phone": "4707500217",
  "address": "86 Commercial Center",
  "linked_in": "",
  "created_at": "2024-03-09 07:58:58",
  "id": 65,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Franklyn",
  "last_name": "Kibby",
  "job_title": "fkibby1t@friendfeed.com",
  "company": "Heidenreich and Sons",
  "business_email": "fkibby1t@constantcontact.com",
  "personal_email": "fkibby1t@imageshack.us",
  "business_phone": "6711432591",
  "personal_phone": "9154315454",
  "address": "88298 Prairieview Drive",
  "linked_in": "",
  "created_at": "2023-11-01 01:40:38",
  "id": 66,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Krisha",
  "last_name": "De Domenicis",
  "job_title": "kdedomenicis1u@patch.com",
  "company": "Cremin, Hammes and Emard",
  "business_email": "kdedomenicis1u@123-reg.co.uk",
  "personal_email": "kdedomenicis1u@t.co",
  "business_phone": "9682424945",
  "personal_phone": "6114449791",
  "address": "554 Boyd Center",
  "linked_in": "",
  "created_at": "2024-03-04 16:34:32",
  "id": 67,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Didi",
  "last_name": "Bolam",
  "job_title": "dbolam1v@google.ru",
  "company": "Herman-Volkman",
  "business_email": "dbolam1v@jiathis.com",
  "personal_email": "dbolam1v@sphinn.com",
  "business_phone": "5778051773",
  "personal_phone": "8936466973",
  "address": "00465 Manitowish Trail",
  "linked_in": "",
  "created_at": "2024-04-18 03:17:54",
  "id": 68,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Tod",
  "last_name": "St Leger",
  "job_title": "tstleger1w@cdbaby.com",
  "company": "Ritchie-Monahan",
  "business_email": "tstleger1w@weebly.com",
  "personal_email": "tstleger1w@fastcompany.com",
  "business_phone": "4389722477",
  "personal_phone": "5031709036",
  "address": "8 Village Avenue",
  "linked_in": "",
  "created_at": "2024-07-17 02:21:11",
  "id": 69,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Thaine",
  "last_name": "Clamp",
  "job_title": "tclamp1x@imgur.com",
  "company": "Kilback, Rice and Ondricka",
  "business_email": "tclamp1x@pagesperso-orange.fr",
  "personal_email": "tclamp1x@privacy.gov.au",
  "business_phone": "3014801731",
  "personal_phone": "9204353421",
  "address": "28 Almo Place",
  "linked_in": "",
  "created_at": "2024-10-04 07:02:18",
  "id": 70,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Klarrisa",
  "last_name": "Lovick",
  "job_title": "klovick1y@slideshare.net",
  "company": "Donnelly Inc",
  "business_email": "klovick1y@netvibes.com",
  "personal_email": "klovick1y@dmoz.org",
  "business_phone": "9737899814",
  "personal_phone": "5179234103",
  "address": "1520 Messerschmidt Pass",
  "linked_in": "",
  "created_at": "2023-12-31 17:55:48",
  "id": 71,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Bucky",
  "last_name": "Gaffer",
  "job_title": "bgaffer1z@github.com",
  "company": "Harvey-Rowe",
  "business_email": "bgaffer1z@youtu.be",
  "personal_email": "bgaffer1z@bloglovin.com",
  "business_phone": "2572156628",
  "personal_phone": "5125399612",
  "address": "5509 Bluestem Point",
  "linked_in": "",
  "created_at": "2023-10-29 14:11:07",
  "id": 72,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Normy",
  "last_name": "Kippen",
  "job_title": "nkippen20@hugedomains.com",
  "company": "Bayer-Wyman",
  "business_email": "nkippen20@t.co",
  "personal_email": "nkippen20@ycombinator.com",
  "business_phone": "4412310339",
  "personal_phone": "2859974923",
  "address": "2807 Butterfield Park",
  "linked_in": "",
  "created_at": "2024-02-03 06:55:37",
  "id": 73,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Colas",
  "last_name": "Sandilands",
  "job_title": "csandilands21@nbcnews.com",
  "company": "Auer, Jacobson and Yundt",
  "business_email": "csandilands21@hp.com",
  "personal_email": "csandilands21@360.cn",
  "business_phone": "7195844133",
  "personal_phone": "8563625491",
  "address": "2 Starling Park",
  "linked_in": "",
  "created_at": "2024-07-17 12:57:24",
  "id": 74,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Andriette",
  "last_name": "Sellack",
  "job_title": "asellack22@dell.com",
  "company": "Bradtke-Beatty",
  "business_email": "asellack22@jigsy.com",
  "personal_email": "asellack22@wikimedia.org",
  "business_phone": "4038149415",
  "personal_phone": "9893006873",
  "address": "7 Claremont Trail",
  "linked_in": "",
  "created_at": "2024-05-17 22:35:36",
  "id": 75,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Read",
  "last_name": "Iwanczyk",
  "job_title": "riwanczyk23@phpbb.com",
  "company": "Cronin LLC",
  "business_email": "riwanczyk23@moonfruit.com",
  "personal_email": "riwanczyk23@sbwire.com",
  "business_phone": "9015144083",
  "personal_phone": "9851954159",
  "address": "237 Red Cloud Terrace",
  "linked_in": "",
  "created_at": "2024-06-09 00:09:19",
  "id": 76,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Hyacinthe",
  "last_name": "Shillabeare",
  "job_title": "hshillabeare24@jiathis.com",
  "company": "Rath LLC",
  "business_email": "hshillabeare24@indiatimes.com",
  "personal_email": "hshillabeare24@ucsd.edu",
  "business_phone": "1643577303",
  "personal_phone": "7294061806",
  "address": "47 Ridge Oak Junction",
  "linked_in": "",
  "created_at": "2024-06-07 16:27:29",
  "id": 77,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Vic",
  "last_name": "Mayoh",
  "job_title": "vmayoh25@soundcloud.com",
  "company": "Langworth-Hand",
  "business_email": "vmayoh25@de.vu",
  "personal_email": "vmayoh25@multiply.com",
  "business_phone": "4239102116",
  "personal_phone": "2531000933",
  "address": "477 Del Mar Parkway",
  "linked_in": "",
  "created_at": "2023-11-13 00:42:23",
  "id": 78,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Torry",
  "last_name": "Fotherby",
  "job_title": "tfotherby26@yandex.ru",
  "company": "Hoeger LLC",
  "business_email": "tfotherby26@fda.gov",
  "personal_email": "tfotherby26@cpanel.net",
  "business_phone": "1222260080",
  "personal_phone": "5207197257",
  "address": "18530 Ruskin Lane",
  "linked_in": "",
  "created_at": "2024-08-21 14:08:06",
  "id": 79,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Orsola",
  "last_name": "Leahy",
  "job_title": "oleahy27@xinhuanet.com",
  "company": "Little, Gulgowski and Maggio",
  "business_email": "oleahy27@psu.edu",
  "personal_email": "oleahy27@guardian.co.uk",
  "business_phone": "2881485617",
  "personal_phone": "8653563435",
  "address": "87 Green Way",
  "linked_in": "",
  "created_at": "2024-05-01 12:02:34",
  "id": 80,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Kori",
  "last_name": "De Benedictis",
  "job_title": "kdebenedictis28@fema.gov",
  "company": "Wunsch, Skiles and Johns",
  "business_email": "kdebenedictis28@icq.com",
  "personal_email": "kdebenedictis28@xinhuanet.com",
  "business_phone": "5656822553",
  "personal_phone": "4454574992",
  "address": "3 Shoshone Place",
  "linked_in": "",
  "created_at": "2024-05-15 21:44:26",
  "id": 81,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Corabelle",
  "last_name": "O'Halligan",
  "job_title": "cohalligan29@spiegel.de",
  "company": "Ledner, Hahn and Hartmann",
  "business_email": "cohalligan29@timesonline.co.uk",
  "personal_email": "cohalligan29@amazon.de",
  "business_phone": "6297292524",
  "personal_phone": "1659236801",
  "address": "908 Everett Way",
  "linked_in": "",
  "created_at": "2023-11-25 04:42:59",
  "id": 82,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Rosie",
  "last_name": "D'Antoni",
  "job_title": "rdantoni2a@ycombinator.com",
  "company": "Breitenberg Inc",
  "business_email": "rdantoni2a@spotify.com",
  "personal_email": "rdantoni2a@ca.gov",
  "business_phone": "2048309092",
  "personal_phone": "5976661940",
  "address": "814 Clarendon Alley",
  "linked_in": "",
  "created_at": "2023-12-30 07:44:27",
  "id": 83,
  "user_id": 1,
  "status": "Open Deals",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Engracia",
  "last_name": "Baggott",
  "job_title": "ebaggott2b@feedburner.com",
  "company": "Ruecker LLC",
  "business_email": "ebaggott2b@issuu.com",
  "personal_email": "ebaggott2b@howstuffworks.com",
  "business_phone": "1402947933",
  "personal_phone": "3003523668",
  "address": "34341 Dryden Way",
  "linked_in": "",
  "created_at": "2024-07-20 13:24:52",
  "id": 84,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Jesse",
  "last_name": "Olden",
  "job_title": "jolden2c@g.co",
  "company": "Stanton Group",
  "business_email": "jolden2c@salon.com",
  "personal_email": "jolden2c@umn.edu",
  "business_phone": "4905492569",
  "personal_phone": "5928994989",
  "address": "165 Pepper Wood Hill",
  "linked_in": "",
  "created_at": "2023-12-19 16:20:19",
  "id": 85,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Manfred",
  "last_name": "Crews",
  "job_title": "mcrews2d@de.vu",
  "company": "Borer, Grant and Lesch",
  "business_email": "mcrews2d@unblog.fr",
  "personal_email": "mcrews2d@linkedin.com",
  "business_phone": "3473193443",
  "personal_phone": "1706932268",
  "address": "38 Elka Drive",
  "linked_in": "",
  "created_at": "2024-09-28 03:46:58",
  "id": 86,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Fields",
  "last_name": "Foster-Smith",
  "job_title": "ffostersmith2e@usatoday.com",
  "company": "Lind Inc",
  "business_email": "ffostersmith2e@qq.com",
  "personal_email": "ffostersmith2e@addthis.com",
  "business_phone": "2541428714",
  "personal_phone": "7972858305",
  "address": "96 Kedzie Plaza",
  "linked_in": "",
  "created_at": "2024-03-14 02:52:48",
  "id": 87,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Anitra",
  "last_name": "Bailes",
  "job_title": "abailes2f@blog.com",
  "company": "Huels-O'Reilly",
  "business_email": "abailes2f@simplemachines.org",
  "personal_email": "abailes2f@altervista.org",
  "business_phone": "1538750537",
  "personal_phone": "5075147994",
  "address": "188 Carioca Road",
  "linked_in": "",
  "created_at": "2024-03-18 05:22:31",
  "id": 88,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Brenna",
  "last_name": "Kermode",
  "job_title": "bkermode2g@usa.gov",
  "company": "Orn, Sauer and DuBuque",
  "business_email": "bkermode2g@alibaba.com",
  "personal_email": "bkermode2g@harvard.edu",
  "business_phone": "9066866159",
  "personal_phone": "9259676436",
  "address": "62 Fair Oaks Drive",
  "linked_in": "",
  "created_at": "2023-12-16 01:36:43",
  "id": 89,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Harrietta",
  "last_name": "Lamblot",
  "job_title": "hlamblot2h@amazon.com",
  "company": "Kshlerin, Berge and Stehr",
  "business_email": "hlamblot2h@smh.com.au",
  "personal_email": "hlamblot2h@ow.ly",
  "business_phone": "5711073121",
  "personal_phone": "4804263434",
  "address": "7 Kim Road",
  "linked_in": "",
  "created_at": "2024-06-19 05:44:05",
  "id": 90,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Alphonso",
  "last_name": "Eastby",
  "job_title": "aeastby2i@zimbio.com",
  "company": "Emard-Walker",
  "business_email": "aeastby2i@discovery.com",
  "personal_email": "aeastby2i@github.com",
  "business_phone": "8414405901",
  "personal_phone": "4118275602",
  "address": "1 Manufacturers Hill",
  "linked_in": "",
  "created_at": "2023-11-26 12:40:17",
  "id": 91,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Peg",
  "last_name": "Sommerly",
  "job_title": "psommerly2j@mtv.com",
  "company": "Schamberger and Sons",
  "business_email": "psommerly2j@un.org",
  "personal_email": "psommerly2j@ucla.edu",
  "business_phone": "2983856341",
  "personal_phone": "5272911148",
  "address": "385 Manufacturers Way",
  "linked_in": "",
  "created_at": "2024-04-25 21:17:16",
  "id": 92,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Anatole",
  "last_name": "Skeemor",
  "job_title": "askeemor2k@dion.ne.jp",
  "company": "Lindgren LLC",
  "business_email": "askeemor2k@squidoo.com",
  "personal_email": "askeemor2k@hhs.gov",
  "business_phone": "4191700169",
  "personal_phone": "2161418628",
  "address": "80 Talisman Terrace",
  "linked_in": "",
  "created_at": "2024-05-12 18:31:30",
  "id": 93,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Cairistiona",
  "last_name": "Kamenar",
  "job_title": "ckamenar2l@marketwatch.com",
  "company": "Hayes LLC",
  "business_email": "ckamenar2l@hao123.com",
  "personal_email": "ckamenar2l@tripadvisor.com",
  "business_phone": "3808194429",
  "personal_phone": "5579182865",
  "address": "837 Montana Terrace",
  "linked_in": "",
  "created_at": "2023-11-18 23:54:35",
  "id": 94,
  "user_id": 1,
  "status": "Open",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Emanuele",
  "last_name": "Bellee",
  "job_title": "ebellee2m@epa.gov",
  "company": "Veum-Gislason",
  "business_email": "ebellee2m@dion.ne.jp",
  "personal_email": "ebellee2m@github.com",
  "business_phone": "8415587488",
  "personal_phone": "6434291851",
  "address": "335 Fallview Parkway",
  "linked_in": "",
  "created_at": "2024-06-17 08:25:48",
  "id": 95,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Robinet",
  "last_name": "Mainstone",
  "job_title": "rmainstone2n@netlog.com",
  "company": "Mueller Group",
  "business_email": "rmainstone2n@ucla.edu",
  "personal_email": "rmainstone2n@i2i.jp",
  "business_phone": "6321271598",
  "personal_phone": "1334103866",
  "address": "44 Scofield Point",
  "linked_in": "",
  "created_at": "2024-02-07 13:48:37",
  "id": 96,
  "user_id": 1,
  "status": "Closed",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Noak",
  "last_name": "Shadwick",
  "job_title": "nshadwick2o@drupal.org",
  "company": "Haag Inc",
  "business_email": "nshadwick2o@netscape.com",
  "personal_email": "nshadwick2o@oakley.com",
  "business_phone": "9293136256",
  "personal_phone": "5414642474",
  "address": "82002 Clarendon Court",
  "linked_in": "",
  "created_at": "2023-11-12 17:09:52",
  "id": 97,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Maurita",
  "last_name": "Oen",
  "job_title": "moen2p@1und1.de",
  "company": "Orn, Metz and Champlin",
  "business_email": "moen2p@soundcloud.com",
  "personal_email": "moen2p@google.de",
  "business_phone": "6185986758",
  "personal_phone": "2807021591",
  "address": "90 Drewry Point",
  "linked_in": "",
  "created_at": "2024-07-05 10:51:35",
  "id": 98,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Katya",
  "last_name": "Meldrum",
  "job_title": "kmeldrum2q@mayoclinic.com",
  "company": "McLaughlin, Satterfield and Lowe",
  "business_email": "kmeldrum2q@disqus.com",
  "personal_email": "kmeldrum2q@about.me",
  "business_phone": "6495766391",
  "personal_phone": "7224102770",
  "address": "8 Steensland Street",
  "linked_in": "",
  "created_at": "2024-10-13 07:26:47",
  "id": 99,
  "user_id": 1,
  "status": "In Progress",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}, {
  "first_name": "Paula",
  "last_name": "Jagson",
  "job_title": "pjagson2r@accuweather.com",
  "company": "Boyle-VonRueden",
  "business_email": "pjagson2r@blog.com",
  "personal_email": "pjagson2r@myspace.com",
  "business_phone": "9641906944",
  "personal_phone": "5117357058",
  "address": "0 Division Plaza",
  "linked_in": "",
  "created_at": "2024-08-03 00:52:49",
  "id": 100,
  "user_id": 1,
  "status": "New",
  "comments": "",
  "profile_picture": "",
  "updated_at": null
}];
